@Vechile_Part_HostAddress = http://localhost:5019

GET {{Vechile_Part_HostAddress}}/api/admin/financial-reports/monthly
Accept: application/json

###

POST {{Vechile_Part_HostAddress}}/api/customers/self-register
Content-Type: application/json

###

{
  "fullName": "Test Customer",
  "phone": "9800000000",
  "email": "test@example.com",
  "password": "StrongPass123!"
}

###

GET {{Vechile_Part_HostAddress}}/api/customers/{{customerId}}/profile
Accept: application/json

###

# Response
