@Vechile_Part_HostAddress = http://localhost:5019

GET {{Vechile_Part_HostAddress}}/api/admin/financial-reports/monthly
Accept: application/json

###

GET {{Vechile_Part_HostAddress}}/api/admin/low-stock?threshold=10
Accept: application/json

###

GET {{Vechile_Part_HostAddress}}/api/staff/customer-reports
Accept: application/json

###

# Response
